#!/usr/bin/with-contenv bashio
set -euo pipefail

readonly CODEX_DATA_DIR="/config/codex"
readonly TERMINAL_INDEX="/tmp/ha-codex-terminal.html"

mkdir -p "${CODEX_DATA_DIR}"

# Persist the ChatGPT session and Codex settings in the add-on's own storage.
# The CLI binary is installed under /opt/codex at build time, so its managed
# package files are kept separate from this runtime configuration directory.
export CODEX_HOME="${CODEX_DATA_DIR}"

FONT_SIZE="$(bashio::config 'terminal_font_size')"
SCROLLBACK="$(bashio::config 'terminal_scrollback')"
THEME="$(bashio::config 'terminal_theme')"
PERSIST="$(bashio::config 'session_persistence')"
PRESERVE_HISTORY="$(bashio::config 'preserve_terminal_history')"
PATCH_COMPATIBILITY_MODE="$(bashio::config 'patch_compatibility_mode')"
MODEL="$(bashio::config 'model')"
HOME_ASSISTANT_CONTROL="$(bashio::config 'home_assistant_control')"
ALLOW_HOME_ASSISTANT_RESTART="$(bashio::config 'allow_home_assistant_restart')"
export HA_CODEX_HOME_ASSISTANT_CONTROL="${HOME_ASSISTANT_CONTROL}"
export HA_CODEX_ALLOW_HOME_ASSISTANT_RESTART="${ALLOW_HOME_ASSISTANT_RESTART}"
export HA_CODEX_PATCH_COMPATIBILITY_MODE="${PATCH_COMPATIBILITY_MODE}"
TERMINAL_MODE="fullscreen"

if [ "${PRESERVE_HISTORY}" = "true" ]; then
  TERMINAL_MODE="inline"
fi

# Keep the durable terminal-session identity stable. Changing it creates a new
# tmux session, which discards the visible browser scrollback users rely on.
# The sign-in menu is evaluated only when Codex is logged out, so it does not
# need a new persistent session name to take effect.
readonly AUTH_FLOW_VERSION="device-code-v2"
readonly SESSION_NAME="home-assistant-codex-${MODEL}-${TERMINAL_MODE}-${AUTH_FLOW_VERSION}"
TTYD_INDEX_ARGS=()

if [ "${PERSIST}" = "true" ]; then
  # tmux keeps Codex alive when Home Assistant closes the Ingress websocket
  # during sidebar navigation. Its mouse mode must stay enabled so wheel and
  # trackpad gestures enter copy mode and navigate tmux's full history buffer
  # instead of being sent to Codex as up/down command-history keys.
  COMMAND="tmux -f /etc/ha-codex-tmux.conf set-option -g history-limit ${SCROLLBACK}; tmux -f /etc/ha-codex-tmux.conf new-session -A -s ${SESSION_NAME} '/usr/local/bin/ha-codex-session ${MODEL} ${TERMINAL_MODE}; exec bash -l'"
else
  COMMAND="exec /usr/local/bin/ha-codex-session ${MODEL} ${TERMINAL_MODE}"
fi

bashio::log.info "Starting HA Codex."
bashio::log.info "Using Codex model: ${MODEL}."
bashio::log.info "Terminal history mode: ${TERMINAL_MODE}."
bashio::log.info "First-time sign-in uses the HA Codex device-code method by default."
bashio::log.info "Patch compatibility mode: ${PATCH_COMPATIBILITY_MODE}."
bashio::log.info "Home Assistant control actions: ${HOME_ASSISTANT_CONTROL}; Core restart: ${ALLOW_HOME_ASSISTANT_RESTART}."

# ttyd bundles its complete browser client inside its executable.  Home
# Assistant's embedded browser can hide the native xterm scrollbar, especially
# on touch devices, so derive that matching page and add an always-visible,
# touch-draggable scroll rail.  This keeps the page in lockstep with the ttyd
# version installed in the add-on instead of maintaining a separate copy.
GZIP_OFFSET="$(LC_ALL=C grep -abo $'\x1f\x8b\x08' /usr/local/bin/ttyd | head -n 1 | LC_ALL=C cut -d: -f1 || true)"
if [ -n "${GZIP_OFFSET}" ]; then
  dd if=/usr/local/bin/ttyd bs=1 skip="${GZIP_OFFSET}" 2>/dev/null | gzip -dc 2>/dev/null > "${TERMINAL_INDEX}" || true

  if [ -s "${TERMINAL_INDEX}" ] && grep -q '</html>' "${TERMINAL_INDEX}"; then
    # ttyd applies --client-option preferences after constructing xterm. Set
    # scrollback in its bundled defaults as well, so xterm allocates the
    # history buffer before any terminal output arrives.
    sed -i "s/fontSize:13,/scrollback:${SCROLLBACK},fontSize:13,/" "${TERMINAL_INDEX}"
    sed -i "s@</head>@<script>window.__HA_CODEX_SCROLLBACK__=${SCROLLBACK};</script></head>@" "${TERMINAL_INDEX}"
    sed -i 's@</head>@<style id="ha-codex-scrollbar-style">#terminal-container{box-sizing:border-box!important;padding-right:36px!important}#terminal-container .terminal{box-sizing:border-box!important;width:100%!important}#ha-codex-scrollbar{position:fixed;z-index:50;top:6px;right:4px;bottom:6px;width:28px;display:flex;flex-direction:column;gap:4px;padding:2px;border-left:1px solid rgba(127,127,127,.32);background:rgba(32,36,45,.86);box-sizing:border-box}#ha-codex-scrollbar[hidden]{display:none}.ha-codex-scroll-button{height:26px;padding:0;border:1px solid #6b5734;border-radius:5px;background:#3a3225;color:#f6c66f;font:700 18px/1 sans-serif;touch-action:manipulation}.ha-codex-scroll-button:focus-visible{outline:2px solid #f6c66f;outline-offset:1px}.ha-codex-scroll-track{position:relative;flex:1;min-height:44px;border-radius:6px;background:#15191f;touch-action:none;cursor:ns-resize}.ha-codex-scroll-thumb{position:absolute;left:3px;right:3px;min-height:28px;border-radius:5px;background:#e6a23c;box-shadow:inset 0 0 0 1px rgba(255,255,255,.35)}.xterm .xterm-viewport{scrollbar-width:none!important}.xterm .xterm-viewport::-webkit-scrollbar{display:none!important}</style></head>@' "${TERMINAL_INDEX}"
    sed -i 's@</body>@<script id="ha-codex-buffer-scrollbar-script">(()=>{const start=()=>{const term=window.term;if(!term||document.getElementById("ha-codex-buffer-scrollbar")){return}const configured=Number(window.__HA_CODEX_SCROLLBACK__);if(Number.isFinite(configured)&&configured>0){term.options.scrollback=configured}document.getElementById("ha-codex-scrollbar")?.remove();const rail=document.createElement("div");const top=document.createElement("button");const bottom=document.createElement("button");const track=document.createElement("div");const thumb=document.createElement("div");rail.id="ha-codex-buffer-scrollbar";rail.className="ha-codex-scrollbar";rail.setAttribute("aria-label","Terminal history controls");top.type="button";top.className="ha-codex-scroll-button";top.textContent="↑";top.setAttribute("aria-label","Scroll to beginning of terminal history");top.title="Beginning of history";bottom.type="button";bottom.className="ha-codex-scroll-button";bottom.textContent="↓";bottom.setAttribute("aria-label","Scroll to latest terminal output");bottom.title="Latest output";track.className="ha-codex-scroll-track";thumb.className="ha-codex-scroll-thumb";track.appendChild(thumb);rail.append(top,track,bottom);document.body.appendChild(rail);let dragging=false;const range=()=>term.buffer.active.baseY;const position=()=>term.buffer.active.viewportY;const sync=()=>{const total=range();const height=track.clientHeight;const thumbHeight=Math.max(28,Math.min(height,height*((term.rows||1)/Math.max(term.buffer.active.length,1))));const available=Math.max(0,height-thumbHeight);thumb.style.height=thumbHeight+"px";thumb.style.transform="translateY("+(total?available*(position()/total):0)+"px)";rail.hidden=total<1};const move=y=>{const rect=track.getBoundingClientRect();const thumbHeight=thumb.getBoundingClientRect().height;const available=Math.max(1,rect.height-thumbHeight);const fraction=Math.max(0,Math.min(1,(y-rect.top-thumbHeight/2)/available));term.scrollLines(Math.round(fraction*range())-position());sync()};top.addEventListener("click",()=>{term.scrollToTop();sync()});bottom.addEventListener("click",()=>{term.scrollToBottom();sync()});track.addEventListener("pointerdown",event=>{dragging=true;track.setPointerCapture(event.pointerId);move(event.clientY);event.preventDefault()});track.addEventListener("pointermove",event=>{if(dragging){move(event.clientY)}});["pointerup","pointercancel","lostpointercapture"].forEach(type=>track.addEventListener(type,()=>{dragging=false}));term.onScroll(sync);window.addEventListener("resize",sync);setInterval(sync,400);sync()};new MutationObserver(start).observe(document.documentElement,{childList:true,subtree:true});start()})();</script></body>@' "${TERMINAL_INDEX}"
    sed -i 's@</body>@<script id="ha-codex-scrollbar-script">(()=>{const start=()=>{const viewport=document.querySelector(".xterm-viewport");if(!viewport||document.getElementById("ha-codex-scrollbar")){return}const rail=document.createElement("div");const top=document.createElement("button");const bottom=document.createElement("button");const track=document.createElement("div");const thumb=document.createElement("div");rail.id="ha-codex-scrollbar";rail.setAttribute("aria-label","Terminal history controls");top.type="button";top.className="ha-codex-scroll-button";top.textContent="↑";top.setAttribute("aria-label","Scroll to beginning of terminal history");top.title="Beginning of history";bottom.type="button";bottom.className="ha-codex-scroll-button";bottom.textContent="↓";bottom.setAttribute("aria-label","Scroll to latest terminal output");bottom.title="Latest output";track.className="ha-codex-scroll-track";thumb.className="ha-codex-scroll-thumb";track.appendChild(thumb);rail.append(top,track,bottom);document.body.appendChild(rail);let dragging=false;const max=()=>Math.max(0,viewport.scrollHeight-viewport.clientHeight);const sync=()=>{const range=max();const height=track.clientHeight;const thumbHeight=Math.max(28,Math.min(height,height*(viewport.clientHeight/Math.max(viewport.scrollHeight,1))));const available=Math.max(0,height-thumbHeight);thumb.style.height=thumbHeight+"px";thumb.style.transform="translateY("+(range?available*(viewport.scrollTop/range):0)+"px)";rail.hidden=range<2};const move=y=>{const rect=track.getBoundingClientRect();const thumbHeight=thumb.getBoundingClientRect().height;const available=Math.max(1,rect.height-thumbHeight);const position=Math.max(0,Math.min(available,y-rect.top-thumbHeight/2));viewport.scrollTop=(position/available)*max();sync()};top.addEventListener("click",()=>{viewport.scrollTop=0;sync()});bottom.addEventListener("click",()=>{viewport.scrollTop=max();sync()});track.addEventListener("pointerdown",event=>{dragging=true;track.setPointerCapture(event.pointerId);move(event.clientY);event.preventDefault()});track.addEventListener("pointermove",event=>{if(dragging){move(event.clientY)}});["pointerup","pointercancel","lostpointercapture"].forEach(type=>track.addEventListener(type,()=>{dragging=false}));viewport.addEventListener("scroll",sync,{passive:true});window.addEventListener("resize",sync);setInterval(sync,400);sync()};new MutationObserver(start).observe(document.documentElement,{childList:true,subtree:true});start()})();</script></body>@' "${TERMINAL_INDEX}"
    sed -i 's/ha-codex-buffer-scrollbar/ha-codex-scrollbar/g' "${TERMINAL_INDEX}"
    # With inline output reaching xterm directly, its native viewport is the
    # authoritative scroll position. Keep it styled when the embedded browser
    # exposes native scrollbars, and add a dedicated xterm-buffer rail below
    # for browsers that hide overlay scrollbars (notably HA's mobile WebView).
    sed -i 's@</head>@<style id="ha-codex-native-scrollbar-style">#terminal-container{padding-right:0!important}#ha-codex-scrollbar{display:none!important}.xterm .xterm-viewport{overflow-y:scroll!important;scrollbar-gutter:stable!important;scrollbar-width:auto!important;scrollbar-color:#e6a23c #20242d!important}.xterm .xterm-viewport::-webkit-scrollbar{display:block!important;width:16px!important;background:#20242d!important}.xterm .xterm-viewport::-webkit-scrollbar-track{background:#20242d!important}.xterm .xterm-viewport::-webkit-scrollbar-thumb{min-height:32px!important;border:3px solid #20242d!important;border-radius:9px!important;background:#e6a23c!important}</style></head>@' "${TERMINAL_INDEX}"
    sed -i 's@</head>@<style id="ha-codex-history-rail-style">#terminal-container{padding-right:38px!important}.ha-codex-history-rail{position:fixed;z-index:2147483647;top:6px;right:4px;bottom:6px;width:30px;display:flex;flex-direction:column;gap:4px;padding:2px;box-sizing:border-box;border-left:1px solid rgba(127,127,127,.45);background:rgba(32,36,45,.94)}.ha-codex-history-rail[hidden]{display:none}.ha-codex-history-button{height:26px;padding:0;border:1px solid #6b5734;border-radius:5px;background:#3a3225;color:#f6c66f;font:700 18px/1 sans-serif;touch-action:manipulation}.ha-codex-history-track{position:relative;flex:1;min-height:44px;border-radius:6px;background:#15191f;touch-action:none;cursor:ns-resize}.ha-codex-history-thumb{position:absolute;left:3px;right:3px;min-height:28px;border-radius:5px;background:#e6a23c;box-shadow:inset 0 0 0 1px rgba(255,255,255,.35)}</style></head>@' "${TERMINAL_INDEX}"
    sed -i 's@</body>@<script id="ha-codex-history-rail-script">(()=>{const start=()=>{const term=window.term;if(!term||document.getElementById("ha-codex-history-rail")){return}const rail=document.createElement("div"),top=document.createElement("button"),bottom=document.createElement("button"),track=document.createElement("div"),thumb=document.createElement("div");rail.id="ha-codex-history-rail";rail.className="ha-codex-history-rail";rail.setAttribute("aria-label","Terminal history controls");top.type=bottom.type="button";top.className=bottom.className="ha-codex-history-button";top.textContent="↑";bottom.textContent="↓";top.setAttribute("aria-label","Scroll to beginning of terminal history");bottom.setAttribute("aria-label","Scroll to latest terminal output");track.className="ha-codex-history-track";thumb.className="ha-codex-history-thumb";track.appendChild(thumb);rail.append(top,track,bottom);document.body.appendChild(rail);let dragging=false;const range=()=>Math.max(0,term.buffer.active.baseY);const position=()=>Math.max(0,term.buffer.active.viewportY);const sync=()=>{const total=range(),height=track.clientHeight,thumbHeight=Math.max(28,Math.min(height,height*((term.rows||1)/Math.max(term.buffer.active.length,1)))),available=Math.max(0,height-thumbHeight);thumb.style.height=thumbHeight+"px";thumb.style.transform="translateY("+(total?available*position()/total:0)+"px)";rail.hidden=total<1};const move=y=>{const rect=track.getBoundingClientRect(),thumbHeight=thumb.getBoundingClientRect().height,available=Math.max(1,rect.height-thumbHeight),fraction=Math.max(0,Math.min(1,(y-rect.top-thumbHeight/2)/available));term.scrollLines(Math.round(fraction*range())-position());sync()};top.addEventListener("click",()=>{term.scrollToTop();sync()});bottom.addEventListener("click",()=>{term.scrollToBottom();sync()});track.addEventListener("pointerdown",event=>{dragging=true;track.setPointerCapture(event.pointerId);move(event.clientY);event.preventDefault()});track.addEventListener("pointermove",event=>{if(dragging){move(event.clientY)}});["pointerup","pointercancel","lostpointercapture"].forEach(type=>track.addEventListener(type,()=>{dragging=false}));const host=document.querySelector("#terminal-container");host?.addEventListener("wheel",event=>{if(range()>0&&Math.abs(event.deltaY)>0){term.scrollLines(Math.sign(event.deltaY)*Math.max(1,Math.round(Math.abs(event.deltaY)/30)));sync();event.preventDefault()}},{capture:true,passive:false});term.onScroll(sync);window.addEventListener("resize",sync);setInterval(sync,250);sync()};new MutationObserver(start).observe(document.documentElement,{childList:true,subtree:true});start()})();</script></body>@' "${TERMINAL_INDEX}"
    # ttyd 1.7.7 keeps its Xterm object private, so integrate with its public
    # viewport element rather than a non-existent window.term global.
    sed -i 's@</body>@<script id="ha-codex-viewport-history-rail-script">(()=>{let retry;const start=()=>{const viewport=document.querySelector(".xterm-viewport");if(!viewport||document.getElementById("ha-codex-viewport-history-rail")){return}clearInterval(retry);const rail=document.createElement("div"),top=document.createElement("button"),bottom=document.createElement("button"),track=document.createElement("div"),thumb=document.createElement("div");rail.id="ha-codex-viewport-history-rail";rail.className="ha-codex-history-rail";rail.setAttribute("aria-label","Terminal history controls");top.type=bottom.type="button";top.className=bottom.className="ha-codex-history-button";top.textContent="↑";bottom.textContent="↓";top.setAttribute("aria-label","Scroll to beginning of terminal history");bottom.setAttribute("aria-label","Scroll to latest terminal output");track.className="ha-codex-history-track";thumb.className="ha-codex-history-thumb";track.appendChild(thumb);rail.append(top,track,bottom);document.body.appendChild(rail);let dragging=false;const max=()=>Math.max(0,viewport.scrollHeight-viewport.clientHeight);const sync=()=>{const range=max(),height=track.clientHeight,thumbHeight=Math.max(28,Math.min(height,height*(viewport.clientHeight/Math.max(viewport.scrollHeight,1)))),available=Math.max(0,height-thumbHeight);thumb.style.height=thumbHeight+"px";thumb.style.transform="translateY("+(range?available*viewport.scrollTop/range:0)+"px)";rail.hidden=range<1};const move=y=>{const rect=track.getBoundingClientRect(),thumbHeight=thumb.getBoundingClientRect().height,available=Math.max(1,rect.height-thumbHeight),position=Math.max(0,Math.min(available,y-rect.top-thumbHeight/2));viewport.scrollTop=(position/available)*max();sync()};top.addEventListener("click",()=>{viewport.scrollTop=0;sync()});bottom.addEventListener("click",()=>{viewport.scrollTop=max();sync()});track.addEventListener("pointerdown",event=>{dragging=true;track.setPointerCapture(event.pointerId);move(event.clientY);event.preventDefault()});track.addEventListener("pointermove",event=>{if(dragging){move(event.clientY)}});["pointerup","pointercancel","lostpointercapture"].forEach(type=>track.addEventListener(type,()=>{dragging=false}));const host=document.querySelector("#terminal-container");host?.addEventListener("wheel",event=>{if(max()>0&&Math.abs(event.deltaY)>0){viewport.scrollTop+=event.deltaY;sync();event.preventDefault()}},{capture:true,passive:false});viewport.addEventListener("scroll",sync,{passive:true});window.addEventListener("resize",sync);setInterval(sync,250);sync()};retry=setInterval(start,100);start()})();</script></body>@' "${TERMINAL_INDEX}"
    # A persistent tmux session owns copy-mode position, so xterm may not have
    # a native scrollbar range even though wheel history navigation works.
    # Keep this rail visible and forward its controls through the same xterm
    # wheel path used by a physical mouse or trackpad.
    sed -i 's@</head>@<style id="ha-codex-tmux-rail-style">.ha-codex-tmux-rail{position:fixed;z-index:2147483647;top:6px;right:4px;bottom:6px;width:30px;display:flex;flex-direction:column;gap:4px;padding:2px;box-sizing:border-box;border-left:1px solid rgba(127,127,127,.45);background:rgba(32,36,45,.94)}.ha-codex-tmux-rail button{height:26px;padding:0;border:1px solid #6b5734;border-radius:5px;background:#3a3225;color:#f6c66f;font:700 18px/1 sans-serif}.ha-codex-tmux-track{position:relative;flex:1;min-height:44px;border-radius:6px;background:#15191f;touch-action:none;cursor:ns-resize}.ha-codex-tmux-thumb{position:absolute;left:3px;right:3px;top:3px;height:48px;border-radius:5px;background:#e6a23c;box-shadow:inset 0 0 0 1px rgba(255,255,255,.35)}</style></head>@' "${TERMINAL_INDEX}"
    # HA's embedded browser can defer injected scripts after the terminal is
    # painted. This CSS-only fallback guarantees a visible history indicator
    # while tmux continues to provide the working wheel/trackpad navigation.
    sed -i 's@</head>@<style id="ha-codex-history-indicator-style">#terminal-container::before{content:"";position:fixed;z-index:2147483646;top:8px;right:5px;bottom:8px;width:12px;border-radius:7px;background:#15191f;box-shadow:inset 0 0 0 1px #63543a;pointer-events:none}#terminal-container::after{content:"";position:fixed;z-index:2147483647;top:12px;right:7px;width:8px;height:56px;border-radius:6px;background:#e6a23c;box-shadow:inset 0 0 0 1px rgba(255,255,255,.45);pointer-events:none}</style></head>@' "${TERMINAL_INDEX}"
    sed -i 's@</head>@<style id="ha-codex-click-scrollbar-style">#ha-codex-click-scrollbar{position:fixed;z-index:2147483648;top:8px;right:4px;bottom:8px;width:18px;display:flex;flex-direction:column;gap:4px;padding:1px;box-sizing:border-box}#ha-codex-click-scrollbar button{height:24px;padding:0;border:1px solid #6b5734;border-radius:5px;background:#3a3225;color:#f6c66f;font:700 16px/1 sans-serif}#ha-codex-click-scroll-track{position:relative;flex:1;border:1px solid #63543a;border-radius:7px;background:#15191f;cursor:ns-resize;touch-action:none}#ha-codex-click-scroll-thumb{position:absolute;top:3px;left:3px;right:3px;height:56px;border-radius:5px;background:#e6a23c;box-shadow:inset 0 0 0 1px rgba(255,255,255,.45);pointer-events:none}</style></head>@' "${TERMINAL_INDEX}"
    sed -i 's@</body>@<div id="ha-codex-click-scrollbar" aria-label="Terminal history controls"><button type="button" aria-label="Scroll terminal history to top" onclick="var t=window.term;if(t){t.scrollToTop()}">↑</button><div id="ha-codex-click-scroll-track" role="scrollbar" aria-label="Terminal history" onclick="var t=window.term,b=t&&t.buffer.active;if(b){var r=this.getBoundingClientRect(),f=Math.max(0,Math.min(1,(event.clientY-r.top)/r.height));t.scrollLines(Math.round(f*b.baseY)-b.viewportY)}" onpointerdown="this.setPointerCapture(event.pointerId);this._dragging=true;this.onclick(event)" onpointermove="if(this._dragging){this.onclick(event)}" onpointerup="this._dragging=false" onpointercancel="this._dragging=false"><div id="ha-codex-click-scroll-thumb"></div></div><button type="button" aria-label="Scroll terminal history to bottom" onclick="var t=window.term;if(t){t.scrollToBottom()}">↓</button></div></body>@' "${TERMINAL_INDEX}"
    sed -i 's@</body>@<script id="ha-codex-tmux-rail-script">(()=>{let retry;const start=()=>{const term=window.term;if(!term||document.getElementById("ha-codex-tmux-rail")){return}clearInterval(retry);const rail=document.createElement("div"),up=document.createElement("button"),down=document.createElement("button"),track=document.createElement("div"),thumb=document.createElement("div"),target=term.element||document.querySelector(".xterm");rail.id="ha-codex-tmux-rail";rail.className="ha-codex-tmux-rail";rail.setAttribute("aria-label","Terminal history controls");up.type=down.type="button";up.textContent="↑";down.textContent="↓";up.setAttribute("aria-label","Scroll terminal history up");down.setAttribute("aria-label","Scroll terminal history down");track.className="ha-codex-tmux-track";thumb.className="ha-codex-tmux-thumb";track.appendChild(thumb);rail.append(up,track,down);document.body.appendChild(rail);const wheel=delta=>target?.dispatchEvent(new WheelEvent("wheel",{bubbles:true,cancelable:true,deltaY:delta,deltaMode:0,view:window}));const step=delta=>{for(let i=0;i<4;i+=1){wheel(delta)}};up.addEventListener("click",()=>step(-180));down.addEventListener("click",()=>step(180));let dragging=false,lastY=0;track.addEventListener("pointerdown",event=>{dragging=true;lastY=event.clientY;track.setPointerCapture(event.pointerId);event.preventDefault()});track.addEventListener("pointermove",event=>{if(!dragging){return}const delta=(event.clientY-lastY)*12;lastY=event.clientY;if(delta){wheel(delta)}});["pointerup","pointercancel","lostpointercapture"].forEach(type=>track.addEventListener(type,()=>{dragging=false}))};retry=setInterval(start,100);start()})();</script></body>@' "${TERMINAL_INDEX}"
    TTYD_INDEX_ARGS=(--index "${TERMINAL_INDEX}")
    bashio::log.info "Enabled visible terminal scrollbar."
  else
    bashio::log.warning "Could not prepare the enhanced terminal scrollbar; using ttyd's standard page."
  fi
else
  bashio::log.warning "Could not locate ttyd's browser client; using ttyd's standard page."
fi

exec /usr/local/bin/ttyd \
  --writable \
  --port 7681 \
  --terminal-type xterm-256color \
  --client-option "fontSize=${FONT_SIZE}" \
  --client-option "scrollback=${SCROLLBACK}" \
  --client-option "theme=${THEME}" \
  "${TTYD_INDEX_ARGS[@]}" \
  bash -lc "${COMMAND}"
